import './globals.css'
import { Toaster } from 'sonner'

export const metadata = {
  title: 'Sportify Frontend',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {children}
        <Toaster position="top-right" richColors />
      </body>
    </html>
  )
}
