import './globals.css'
import { Toaster } from 'sonner'
import { Noto_Sans_TC } from 'next/font/google'
import { AuthProvider } from '@/contexts/auth-context'

const notoSansTC = Noto_Sans_TC({
  subsets: ['traditional-chinese'],
  weight: ['400', '700'],
  display: 'swap',
})

export const metadata = {
  title: 'Sportify Frontend',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <AuthProvider>
      <html lang="zh-Hant">
        <body className={notoSansTC.className}>
          {children}
          <Toaster position="top-right" richColors />
        </body>
      </html>
    </AuthProvider>
  )
}
